// Command docgen produces auto-generated reference documentation
// for aichronicles. Lives outside the production build (run via
// `go run ./tools/docgen <subcommand>`); the generated output goes
// to docs/reference/.
//
// Three subcommands, each writing one or more files under
// docs/reference/:
//
//	cli        per-subcommand markdown via cobra.GenMarkdownTree
//	schema     SQL schema reference assembled from the embedded migrations
//	detectors  redaction detector list pulled from redact.BuiltinDetectors
//
// All three are idempotent: re-running on unchanged inputs produces
// byte-identical output. CI uses `make docs-check` to fail when
// committed docs drift from the source of truth.
package main

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra/doc"

	"github.com/toabctl/aichronicles/internal/cli"
	"github.com/toabctl/aichronicles/internal/redact"
	"github.com/toabctl/aichronicles/internal/store"
)

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(2)
	}
	out := "docs/reference"
	switch os.Args[1] {
	case "cli":
		mustExitOK(genCLI(filepath.Join(out, "cli")))
	case "schema":
		mustExitOK(genSchema(filepath.Join(out, "schema.md")))
	case "detectors":
		mustExitOK(genDetectors(filepath.Join(out, "redaction-detectors.md")))
	default:
		usage()
		os.Exit(2)
	}
}

func usage() {
	fmt.Fprintln(os.Stderr, "usage: docgen {cli|schema|detectors}")
}

func mustExitOK(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "docgen:", err)
		os.Exit(1)
	}
}

// --- cli subcommand reference -----------------------------------

// genCLI writes one markdown file per cobra subcommand into outDir
// using cobra/doc.GenMarkdownTree. The generator stamps every page
// with a footer containing the date the page was generated; we
// override the footer to remain stable so commits don't churn.
func genCLI(outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	// Wipe any stale files so renamed commands don't leave orphans.
	entries, err := os.ReadDir(outDir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".md") {
			if err := os.Remove(filepath.Join(outDir, e.Name())); err != nil {
				return err
			}
		}
	}

	root := cli.NewRootCmd()
	root.DisableAutoGenTag = true // suppress "auto generated by spf13/cobra on …"

	// Custom hyperlink + filename handlers keep the output flat
	// (one .md per command, hyphenated names) and link with relative
	// paths that work both on GitHub and under MkDocs Material.
	linkHandler := func(name string) string { return "./" + name }
	filePrepender := func(_ string) string { return "" }

	if err := doc.GenMarkdownTreeCustom(root, outDir, filePrepender, linkHandler); err != nil {
		return err
	}

	// Cobra's generator doesn't always end its files with a final
	// newline; the pre-commit end-of-file-fixer would auto-add one
	// and then `make docs-check` would diff. Normalize here so the
	// generator's output matches what the hook produces.
	if err := normalizeFinalNewlines(outDir); err != nil {
		return err
	}

	// Index page so readers landing on docs/reference/cli/ see a
	// table of contents instead of an empty directory listing.
	return writeCLIIndex(outDir)
}

// normalizeFinalNewlines walks dir and rewrites any *.md file that
// doesn't end in a single trailing newline so it does. Idempotent.
func normalizeFinalNewlines(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		p := filepath.Join(dir, e.Name())
		body, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		fixed := strings.TrimRight(string(body), "\n") + "\n"
		if fixed == string(body) {
			continue
		}
		if err := os.WriteFile(p, []byte(fixed), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func writeCLIIndex(outDir string) error {
	entries, err := os.ReadDir(outDir)
	if err != nil {
		return err
	}
	var pages []string
	for _, e := range entries {
		n := e.Name()
		if e.IsDir() || !strings.HasSuffix(n, ".md") || n == "index.md" {
			continue
		}
		pages = append(pages, n)
	}
	sort.Strings(pages)

	var b strings.Builder
	b.WriteString("# CLI reference\n\n")
	b.WriteString("Auto-generated from the live `cobra.Command.Long` strings ")
	b.WriteString("via `make docs-cli`. Edit the source files under ")
	b.WriteString("`internal/cli/`, not these pages.\n\n")
	b.WriteString("## Commands\n\n")
	for _, p := range pages {
		title := strings.TrimSuffix(p, ".md")
		title = strings.ReplaceAll(title, "_", " ")
		fmt.Fprintf(&b, "- [`%s`](./%s)\n", title, p)
	}
	return writeFileWithFinalNewline(filepath.Join(outDir, "index.md"), b.String())
}

// --- schema reference --------------------------------------------

// genSchema embeds every migration file from the store package's
// embedded FS into a single reference page, in numeric order. The
// SQL is the source of truth — prose annotations belong in
// docs/explanation/architecture.md, not here.
func genSchema(out string) error {
	files, err := readMigrations()
	if err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString("# Schema reference\n\n")
	b.WriteString("Every SQL migration shipped in the binary, in apply order. ")
	b.WriteString("Auto-generated from `internal/store/migrations/` via ")
	b.WriteString("`make docs-schema`; edit the SQL files, not this page.\n\n")
	b.WriteString("Schema design rationale lives at ")
	b.WriteString("[../explanation/architecture.md](../explanation/architecture.md).\n\n")

	for _, f := range files {
		fmt.Fprintf(&b, "## `%s`\n\n", f.name)
		b.WriteString("```sql\n")
		b.WriteString(strings.TrimRight(f.body, "\n"))
		b.WriteString("\n```\n\n")
	}

	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return err
	}
	return writeFileWithFinalNewline(out, b.String())
}

type migrationFile struct {
	name string
	body string
}

// readMigrations walks the store package's embedded migrations FS
// in the same order the migration runner does — numeric prefix
// ascending — and returns each file's name + body.
func readMigrations() ([]migrationFile, error) {
	embedded := store.MigrationsFS()
	var files []migrationFile
	err := fs.WalkDir(embedded, "migrations", func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(p, ".sql") {
			return nil
		}
		body, err := fs.ReadFile(embedded, p)
		if err != nil {
			return err
		}
		files = append(files, migrationFile{name: filepath.Base(p), body: string(body)})
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(files, func(i, j int) bool { return files[i].name < files[j].name })
	return files, nil
}

// --- detector reference ------------------------------------------

// genDetectors walks redact.BuiltinDetectors() and emits a table of
// (name, regex) pairs. Order matches registration so the overlap-
// resolution rules described in the threat model align with what's
// printed here.
func genDetectors(out string) error {
	var b strings.Builder
	b.WriteString("# Redaction detector reference\n\n")
	b.WriteString("Auto-generated from `internal/redact/redact.go:builtinDetectors` ")
	b.WriteString("via `make docs-detectors`. The list reflects the production set ")
	b.WriteString("Default() returns; new detectors land here automatically once ")
	b.WriteString("they ship in the source.\n\n")
	b.WriteString("Detectors are listed in registration order. On overlap, the ")
	b.WriteString("first match wins — most specific / longest-prefix patterns are ")
	b.WriteString("registered first by design (so e.g. an Anthropic key is tagged ")
	b.WriteString("`anthropic_api_key`, not the looser `openai_api_key` it would ")
	b.WriteString("also match). See ")
	b.WriteString("[../explanation/threat-model.md](../explanation/threat-model.md) ")
	b.WriteString("for the contract these enforce.\n\n")
	b.WriteString("| # | Pattern | Regex |\n")
	b.WriteString("|---|---|---|\n")

	for i, s := range redact.BuiltinDetectors() {
		d, ok := s.(*redact.Detector)
		if !ok {
			fmt.Fprintf(&b, "| %d | _(non-Detector Scanner: %T)_ | — |\n", i+1, s)
			continue
		}
		fmt.Fprintf(&b, "| %d | `%s` | `%s` |\n", i+1, d.Name, escapeMarkdown(d.RE.String()))
	}
	b.WriteString("\n")

	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return err
	}
	return writeFileWithFinalNewline(out, b.String())
}

// writeFileWithFinalNewline writes s to path, ensuring it ends in
// EXACTLY one newline (not zero, not multiple). The pre-commit
// `end-of-file-fixer` enforces this convention; matching it in the
// generator keeps `make docs-check` from flagging a one-character
// diff after pre-commit auto-fixed the same file.
//
// Specifically: builders that close every section with "\n\n" leave
// a trailing blank line, which end-of-file-fixer then trims down to
// one newline. The first generation matches; the next regeneration
// re-adds the blank line; CI's docs-check sees the diff and fails.
// Trimming all trailing whitespace and re-appending one newline
// makes the output a fixed point of the auto-fixer.
func writeFileWithFinalNewline(path, s string) error {
	s = strings.TrimRight(s, " \t\n\r") + "\n"
	return os.WriteFile(path, []byte(s), 0o644)
}

// escapeMarkdown protects pipe characters in regex patterns so the
// table renders. Backticks already wrap the regex; we just need to
// keep `|` from breaking the column structure.
func escapeMarkdown(s string) string {
	return strings.ReplaceAll(s, "|", `\|`)
}
